require("user.plugins")
require("user.impatient")

require("user.options")
require("user.keymaps")
require("user.which_key")
require("user.autocommands")

require("user.themes")
require("user.headlines")
require("user.treesitter")

require("user.lsp")
require("user.cmp")
require("user.dap")
require("user.navic")
require("user.quickfix")
require("user.neotree")
require("user.neorg")

require("user.telescope_plugin")
require("user.autopairs")
require("user.tabout")
require("user.leap")

require("user.tabby")
require("user.feline")
require("user.alpha")
require("user.symbols_outline")
require("user.toggleterm")
require("user.project")
require("user.fidget")

require("user.harpoon")
require("user.neoscroll")
require("user.indentline")
require("user.illuminate")
require("user.dressing")
require("user.crates")
require("user.comment")
require("user.gitsigns")
