require("user.impatient")

require("user.options")
require("user.keymaps")
require("user.autocommands")

require("user.plugins")

require("user.lsp")
require("user.cmp")
require("user.dap")
require("user.navic")
require("user.quickfix")
require("user.fidget")
require("user.neotree")

require("user.telescope_plugin")
require("user.colorscheme")
require("user.treesitter")
require("user.autopairs")
require("user.tabout")

require("user.which_key")
require("user.alpha")
require("user.symbols_outline")
require("user.comment")
require("user.gitsigns")
require("user.project")
require("user.toggleterm")
require("user.illuminate")
require("user.tabby")
require("user.feline")
require("user.neorg")
require("user.harpoon")
require("user.cinnamon")
require("user.indentline")
require("user.dressing")
require("user.crates")
require("user.headlines")
