-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet
--[[ vim.g.use_nerd_icons = true
if vim.fn.has "mac" == 1 or vim.g.use_nerd_icons then ]]
return {
	kind = {
		Text = " ",
		-- Method = "m ",
		-- Function = " ",
		-- Constructor = " ",
		Method = " ",
		Function = " ",
		Class = " ",
		Constructor = " ",
		Constant = " ",
		Field = " ",
		Variable = " ",
		Property = " ",
		Interface = " ",
		Module = " ",
		Unit = " ",
		Value = " ",
		Enum = " ",
		Keyword = " ",
		-- Keyword = " ",
		Snippet = " ",
		-- Snippet = " ",
		Namespace = " ",
		Color = " ",
		File = " ",
		Reference = " ",
		EnumMember = " ",
		Struct = " ",
		Event = " ",
		Operator = " ",
		TypeParameter = " ",
		-- type
		Array = " ",
		Number = " ",
		String = " ",
		Boolean = "==",
		Object = " ",
		-- documents
		Files = " ",
		Folder = " ",
		OpenFolder = " ",
	},
	type = {
		Array = " ",
		Number = " ",
		String = " ",
		Boolean = "==",
		Object = " ",
	},
	documents = {
		File = "   ",
		Files = " ",
		Folder = " ",
		OpenFolder = " ",
	},
	git = {
		Add = " ",
		Mod = " ",
		Remove = " ",
		Ignore = " ",
		Rename = " ",
		Diff = " ",
		Repo = " ",
		Octoface = " ",
	},
	ui = {
		RightThickCircle = "",
		LeftThickCircle = "",
		RightThinCircle = "",
		LeftThinCircle = "",
		ArrowClosed = " ",
		ArrowOpen = " ",
		Lock = " ",
		Circle = " ",
		BigCircle = " ",
		BigUnfilledCircle = " ",
		Close = " ",
		NewFile = " ",
		Search = " ",
		Lightbulb = " ",
		Project = " ",
		Dashboard = " ",
		History = " ",
		Comment = " ",
		Bug = " ",
		Code = " ",
		Telescope = " ",
		Gear = " ",
		Package = " ",
		List = " ",
		Tag = " ",
		SignIn = " ",
		SignOut = " ",
		Check = " ",
		Fire = " ",
		Note = " ",
		BookMark = " ",
		Pencil = " ",
		ChevronRight = " ",
		Table = " ",
		Calendar = " ",
		CloudDownload = " ",
	},
	diagnostics = {
		Error = " ",
		Warning = " ",
		Information = " ",
		Question = " ",
		Hint = " ",
	},
	misc = {
		Robot = " ",
		Squirrel = " ",
		Tag = " ",
		Watch = " ",
		Smiley = " ",
		Package = " ",
	},
}
